kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: my-app
        static_configs:
          - targets: ["my-app-service:8080"]
            labels:
              app: my-app
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system