# Usar uma imagem base oficial do Python
FROM python:3.8-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos do projeto para o diretório de trabalho
COPY . /app

# Instalar as dependências do projeto
RUN pip install --no-cache-dir Flask prometheus_client

# Expõe a porta 80 para o serviço e a porta 9101 para as métricas do Prometheus
EXPOSE 8080 9101

# Modificar a porta do aplicativo para 80
ENV FLASK_RUN_PORT=8080

# Comando para executar o aplicativo
CMD ["flask", "run", "--host=0.0.0.0"]